#!/usr/bin/env python3
"""Convert the existing DeepFace ArcFace gallery (.npy files) into
functions/api/gallery.js for the Cloudflare demo.

Embeddings are averaged per identity and L2-normalized.

IMPORTANT: this preserves the DeepFace/ArcFace embedding space. For coherent
matching with the client-side ONNX model, regenerate the gallery with that same
model via scripts/regen_gallery_with_model.py.
"""
import json
import os
from collections import OrderedDict

import numpy as np

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
EMB_DIR = os.path.join(ROOT, "face_recognition", "embeddings")
EMB_PATH = os.path.join(EMB_DIR, "arcface_embeddings.npy")
LBL_PATH = os.path.join(EMB_DIR, "arcface_labels.npy")
URL_PATH = os.path.join(EMB_DIR, "arcface_image_urls.npy")
OUT_PATH = os.path.join(ROOT, "functions", "api", "gallery.js")

emb = np.load(EMB_PATH)
lbl = np.load(LBL_PATH)
url = np.load(URL_PATH)

# First URL per identity.
first_url = {}
for l, u in zip(lbl, url):
    first_url.setdefault(l, u)

# Average embeddings per identity.
groups = OrderedDict()
for e, l in zip(emb, lbl):
    groups.setdefault(l, []).append(e)

rows = []
for label, vecs in groups.items():
    avg = np.mean(np.stack(vecs), axis=0)
    norm = np.linalg.norm(avg)
    if norm:
        avg = avg / norm
    rows.append(
        {
            "label": label,
            "image_url": first_url.get(label, ""),
            "embedding": [round(float(x), 6) for x in avg],
        }
    )

lines = [
    "// Generated by scripts/build_gallery.py - do not edit by hand.",
    "// Embeddings: 512-d ArcFace (DeepFace), averaged per identity, L2-normalized.",
    "// IMPORTANT: for coherent matching, regenerate with the client-side ONNX model",
    "// (see scripts/regen_gallery_with_model.py and the plan document).",
    "export default [",
]
for i, r in enumerate(rows):
    emb_str = ", ".join(str(x) for x in r["embedding"])
    sep = "," if i < len(rows) - 1 else ""
    lines.append(
        f'  {{ label: {json.dumps(r["label"])}, image_url: {json.dumps(r["image_url"])}, embedding: [{emb_str}] }}{sep}'
    )
lines.append("];")

os.makedirs(os.path.dirname(OUT_PATH), exist_ok=True)
with open(OUT_PATH, "w", encoding="utf-8") as f:
    f.write("\n".join(lines) + "\n")

print(f"Wrote {OUT_PATH} with {len(rows)} identities:")
for r in rows:
    print(f"  - {r['label']} ({len(r['embedding'])} dims)")
