#!/usr/bin/env python3
"""Regenerate functions/api/gallery.js in the embedding space of a given ONNX
face-embedding model - the SAME model shipped to the browser
(public/model/face_embedding.onnx). Required so /api/verify similarity scores
are meaningful against client-computed embeddings.

Usage:
    python scripts/regen_gallery_with_model.py public/model/face_embedding.onnx

Optional deps: onnxruntime, requests, Pillow  (pip install onnxruntime requests Pillow)

Images: downloads each identity's reference photo (from arcface_image_urls.npy),
center-crops to a square, resizes to 112x112, normalizes to [-1, 1] - the same
preprocessing src/faceEmbedding.js applies. For best accuracy you should crop to
just the face first (the original gallery was built from aligned crops).
"""
import json
import os
import sys

import numpy as np

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
EMB_DIR = os.path.join(ROOT, "face_recognition", "embeddings")
OUT_PATH = os.path.join(ROOT, "functions", "api", "gallery.js")
SIZE = 112


def main():
    if len(sys.argv) < 2:
        print("Usage: python scripts/regen_gallery_with_model.py model.onnx")
        sys.exit(1)

    import onnxruntime as ort
    from PIL import Image
    import requests

    model_path = sys.argv[1]
    session = ort.InferenceSession(model_path, providers=["CPUExecutionProvider"])
    input_name = session.get_inputs()[0].name
    print(f"Model input: {input_name} {session.get_inputs()[0].shape}")

    emb = np.load(os.path.join(EMB_DIR, "arcface_embeddings.npy"))
    lbl = np.load(os.path.join(EMB_DIR, "arcface_labels.npy"))
    url = np.load(os.path.join(EMB_DIR, "arcface_image_urls.npy"))

    first_url = {}
    for l, u in zip(lbl, url):
        first_url.setdefault(l, u)

    def embed(im):
        im = im.convert("RGB").resize((SIZE, SIZE), Image.LANCZOS)
        arr = np.asarray(im, dtype=np.float32) / 127.5 - 1.0  # [-1, 1]
        arr = arr.transpose(2, 0, 1)[None]  # 1,3,112,112
        out = session.run(None, {input_name: arr})[0]
        v = np.asarray(out).flatten().astype(np.float64)
        n = np.linalg.norm(v)
        return v / n if n else v

    rows = []
    seen = set()
    for label in dict.fromkeys(lbl):
        img_url = first_url.get(label, "")
        if not img_url:
            print(f"  ! {label}: no image URL, skipping")
            continue
        try:
            r = requests.get(img_url, timeout=30)
            r.raise_for_status()
            v = embed(Image.open(__import__("io").BytesIO(r.content)))
        except Exception as e:
            print(f"  ! {label}: failed ({e}); skipping")
            continue
        rows.append({"label": label, "image_url": img_url, "embedding": [round(float(x), 6) for x in v]})
        seen.add(label)
        print(f"  - {label} ({len(rows[-1]['embedding'])} dims)")

    lines = [
        "// Generated by scripts/regen_gallery_with_model.py - do not edit by hand.",
        f"// Embeddings: {len(rows)} identities from {os.path.basename(model_path)}, L2-normalized.",
        "export default [",
    ]
    for i, r in enumerate(rows):
        emb_str = ", ".join(str(x) for x in r["embedding"])
        sep = "," if i < len(rows) - 1 else ""
        lines.append(
            f'  {{ label: {json.dumps(r["label"])}, image_url: {json.dumps(r["image_url"])}, embedding: [{emb_str}] }}{sep}'
        )
    lines.append("];")

    with open(OUT_PATH, "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")
    print(f"Wrote {OUT_PATH}")


if __name__ == "__main__":
    main()
